# Generated by Django 4.1.5 on 2023-01-26 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractMaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_due_date', models.DateField()),
                ('rent_amount', models.FloatField()),
                ('deposit_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(default=None, max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='rg',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='owner',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='immobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('address_number', models.IntegerField()),
                ('complement', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('biding_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractMaker.contract')),
                ('biding_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractMaker.owner')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='biding_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractMaker.owner'),
        ),
        migrations.AddField(
            model_name='contract',
            name='biding_renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractMaker.renter'),
        ),
    ]
